#!groovy

// Generated by IBM TransformationAdvisor
// Wed Jun 26 13:30:40 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'plantsbywebspherev8'
    mvnCommands = '--version'
    test='false'
}